"""
Django management command to generate weekly development reports.
Can be run from CLI for testing or scheduled via cron.
"""

from django.core.management.base import BaseCommand, CommandError
from django.contrib.auth.models import User
from datetime import datetime, timedelta

from Inventory.utils.report_generator import WeeklyReportGenerator


class Command(BaseCommand):
    help = 'Generate and send weekly development report'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--days',
            type=int,
            default=7,
            help='Number of days to include in report (default: 7)'
        )
        
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Generate report without sending email'
        )
        
        parser.add_argument(
            '--recipients',
            nargs='+',
            help='Email recipients (space-separated)'
        )
        
        parser.add_argument(
            '--cc',
            nargs='+',
            help='CC recipients (space-separated)'
        )
        
        parser.add_argument(
            '--notes',
            type=str,
            default='',
            help='Custom notes to include in report'
        )
        
        parser.add_argument(
            '--user',
            type=str,
            help='Username of the user generating the report'
        )
    
    def handle(self, *args, **options):
        days = options['days']
        dry_run = options['dry_run']
        recipients = options.get('recipients')
        cc_recipients = options.get('cc')
        custom_notes = options.get('notes', '')
        username = options.get('user')
        
        # Get user if specified
        user = None
        if username:
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                raise CommandError(f'User "{username}" does not exist')
        
        # Display configuration
        self.stdout.write(self.style.SUCCESS('=' * 70))
        self.stdout.write(self.style.SUCCESS('WEEKLY DEVELOPMENT REPORT GENERATOR'))
        self.stdout.write(self.style.SUCCESS('=' * 70))
        self.stdout.write('')
        
        start_date = datetime.now().date() - timedelta(days=days)
        end_date = datetime.now().date()
        
        self.stdout.write(f'Report Period: {start_date} to {end_date} ({days} days)')
        self.stdout.write(f'Generated By: {user.username if user else "System"}')
        self.stdout.write(f'Mode: {"DRY RUN (no email sent)" if dry_run else "LIVE (email will be sent)"}')
        
        if recipients:
            self.stdout.write(f'Recipients: {", ".join(recipients)}')
        if cc_recipients:
            self.stdout.write(f'CC: {", ".join(cc_recipients)}')
        if custom_notes:
            self.stdout.write(f'Custom Notes: {custom_notes[:100]}...')
        
        self.stdout.write('')
        self.stdout.write(self.style.WARNING('Generating report...'))
        self.stdout.write('')
        
        try:
            # Generate report
            generator = WeeklyReportGenerator(days=days)
            report = generator.generate_report(
                user=user,
                custom_notes=custom_notes,
                recipients=recipients,
                cc_recipients=cc_recipients,
                dry_run=dry_run
            )
            
            # Display results
            self.stdout.write(self.style.SUCCESS('✓ Report generated successfully!'))
            self.stdout.write('')
            self.stdout.write(f'Report ID: {report.report_id}')
            self.stdout.write(f'Status: {report.get_status_display()}')
            self.stdout.write('')
            
            self.stdout.write(self.style.SUCCESS('Statistics:'))
            self.stdout.write(f'  • Commits Analyzed: {report.commits_analyzed}')
            self.stdout.write(f'  • Files Scanned: {report.files_scanned}')
            self.stdout.write(f'  • Migrations Found: {report.migrations_found}')
            self.stdout.write('')
            
            self.stdout.write(self.style.SUCCESS('Report Sections:'))
            self.stdout.write(f'  • Executive Summary: {len(report.executive_summary)} characters')
            self.stdout.write(f'  • New Features: {len(report.new_features.splitlines())} items')
            self.stdout.write(f'  • Bug Fixes: {len(report.bug_fixes.splitlines())} items')
            self.stdout.write(f'  • Database Changes: {len(report.database_changes.splitlines())} items')
            self.stdout.write('')
            
            if dry_run:
                self.stdout.write(self.style.WARNING('DRY RUN - Email not sent'))
                self.stdout.write('')
                self.stdout.write('Preview of email content:')
                self.stdout.write('-' * 70)
                self.stdout.write(report.plain_text_content[:1000])
                if len(report.plain_text_content) > 1000:
                    self.stdout.write('...(truncated)')
                self.stdout.write('-' * 70)
            else:
                self.stdout.write(self.style.SUCCESS(f'✓ Email sent to: {report.recipients}'))
                if report.cc_recipients:
                    self.stdout.write(f'  CC: {report.cc_recipients}')
            
            self.stdout.write('')
            self.stdout.write(self.style.SUCCESS('=' * 70))
            self.stdout.write(self.style.SUCCESS('REPORT GENERATION COMPLETE'))
            self.stdout.write(self.style.SUCCESS('=' * 70))
        
        except Exception as e:
            self.stdout.write('')
            self.stdout.write(self.style.ERROR('✗ Report generation failed!'))
            self.stdout.write(self.style.ERROR(f'Error: {str(e)}'))
            self.stdout.write('')
            
            # Show traceback in verbose mode
            import traceback
            self.stdout.write(self.style.ERROR('Traceback:'))
            self.stdout.write(traceback.format_exc())
            
            raise CommandError(f'Failed to generate report: {str(e)}')
