"""
Django settings for Inventory_management_system project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import logging
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# True while running the Django test runner (manage.py test / pytest).
TESTING = ('test' in sys.argv) or ('pytest' in sys.modules)

# ---------------------------------------------------------------------------
# Sentry Error Monitoring (only when SENTRY_DSN is set, typically production)
# ---------------------------------------------------------------------------
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.2,      # 20 % performance monitoring
            send_default_pii=True,       # Attach user context to events
            environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        )
    except ImportError:
        logging.warning("sentry-sdk not installed; Sentry error monitoring disabled.")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Azure App Service detection
# ---------------------------------------------------------------------------
# Azure App Service automatically sets WEBSITE_SITE_NAME on every container.
# We use it to: (a) pick a persistent path for the SQLite file (Azure wipes
# everything outside /home/ between deploys/restarts), and (b) drive sane
# production defaults even when DJANGO_DEBUG hasn't been configured yet.
ON_AZURE_APP_SERVICE = bool(os.environ.get('WEBSITE_SITE_NAME'))

# /home/ is the persistent mount on Azure App Service Linux. Everything else
# (including the deployment dir under /tmp/<hash>/) is ephemeral.
AZURE_PERSISTENT_DATA_DIR = '/home/site/data'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

from django.core.exceptions import ImproperlyConfigured

# SECURITY WARNING: don't run with debug turned on in production!
# Resolution order:
#   1. DJANGO_DEBUG env var (explicit override -- wins everywhere).
#   2. On Azure App Service (WEBSITE_SITE_NAME set), default to False so
#      we don't leak the settings page even if no env var is configured.
#   3. Local dev default: True.
_debug_env = os.getenv('DJANGO_DEBUG')
if _debug_env is not None:
    DEBUG = _debug_env.lower() == 'true'
elif ON_AZURE_APP_SERVICE:
    DEBUG = False
else:
    DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.environ.get('DJANGO_SECRET_KEY')
if _secret_key:
    SECRET_KEY = _secret_key
elif DEBUG:
    SECRET_KEY = 'django-insecure-local-dev-only-do-not-use-in-production'
else:
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable is required in production. "
        "Set it in your deployment environment."
    )

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'testserver',
    'moen-ims.org',
    '.moen-ims.org',
    'www.moen-ims.org',
    'moen-ims-fegfgqf3c5frejfv.uksouth-01.azurewebsites.net',
    '169.254.129.3',  # Azure internal IP
    '*.azurewebsites.net',  # Azure app service domains
]

if not DEBUG:
    # Static assets are collected into `staticfiles/`. The WhiteNoise
    # (compressed, manifest-hashed) backend is configured in STORAGES below.
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Microsoft 365 Configuration
MICROSOFT = {
    "CLIENT_ID":     os.environ.get("MS_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("MS_CLIENT_SECRET", ""),
    "TENANT_ID":     os.environ.get("MS_TENANT_ID", ""),
    "AUTHORITY":     f"https://login.microsoftonline.com/{os.environ.get('MS_TENANT_ID', '')}",
    "REDIRECT_URI":  os.environ.get("MS_REDIRECT_URI", "https://moen-ims-fegfgqf3c5frejfv.uksouth-01.azurewebsites.net/auth/callback/"),
    "SCOPES": [
        "email",
        "User.Read",
        "Mail.Send",
    ],
}
TOKEN_ENCRYPTION_KEY = os.environ.get("TOKEN_ENCRYPTION_KEY")
if not TOKEN_ENCRYPTION_KEY and not DEBUG:
    raise ValueError(
        "TOKEN_ENCRYPTION_KEY environment variable is required in production. "
        "Generate one with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    )
elif not TOKEN_ENCRYPTION_KEY:
    # Dev only: generate an ephemeral key at startup instead of shipping a real
    # key in source control. Tokens encrypted in a previous dev run won't decrypt
    # after a restart -- acceptable for local development.
    from cryptography.fernet import Fernet
    TOKEN_ENCRYPTION_KEY = Fernet.generate_key().decode()
    logging.warning(
        "TOKEN_ENCRYPTION_KEY not set; generated an ephemeral dev key. "
        "Set TOKEN_ENCRYPTION_KEY in your environment for stable tokens."
    )

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript from reading CSRF token
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Ensure request.is_secure() works behind proxies
    
    # Only set cookie domain if we have a canonical host
    if 'CANONICAL_HOST' in os.environ and os.environ['CANONICAL_HOST']:
        domain = os.environ['CANONICAL_HOST']
        if domain.startswith('www.'):
            domain = domain[4:]
        SESSION_COOKIE_DOMAIN = f".{domain}"
        CSRF_COOKIE_DOMAIN = f".{domain}"

# CSRF trusted origins (scheme required). Configure via env in production.
_default_csrf = [
    'https://localhost',
    'https://127.0.0.1',
    'https://moen-ims.org',
    'https://www.moen-ims.org',
    'https://moen-ims-fegfgqf3c5frejfv.uksouth-01.azurewebsites.net',
]
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', ','.join(_default_csrf)).split(',') if o.strip()]

# Ensure request.is_secure() works behind proxies (DO App Platform / Heroku)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Optional: force a single canonical host (e.g., 'www.moen-ims.org') to avoid cross-host cookie issues
# Default to www.moen-ims.org in production if not provided via env. Empty in DEBUG.
CANONICAL_HOST = os.getenv('CANONICAL_HOST', '').strip()

# Enforce HTTPS and secure cookies in production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Share cookies across apex and subdomains. Env can override the default.
    _cookie_domain = os.getenv('COOKIE_DOMAIN', '').strip()
    if _cookie_domain:
        SESSION_COOKIE_DOMAIN = _cookie_domain
        CSRF_COOKIE_DOMAIN = _cookie_domain
    # Strongly enforce HTTPS (optional but recommended)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# BASE_URL for absolute links in emails
BASE_URL = f"https://{CANONICAL_HOST}" if CANONICAL_HOST else "http://localhost:8000"

# Exempt certificate validation path from HTTPS redirect so CA bots can fetch
# HTTP-01 challenges without a valid certificate yet.
# Django's SecurityMiddleware honors this list when SECURE_SSL_REDIRECT is True.
SECURE_REDIRECT_EXEMPT = [r'^\.well-known/']



# Application definition

INSTALLED_APPS = [
    'Inventory',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'audit_log',
    'django.contrib.humanize',
    # Two-Factor Authentication
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'accounts',
    # Brute-force / login-throttling protection (must be installed for auth).
    'axes',
]

MIDDLEWARE = [
    'Inventory.middleware.CanonicalHostRedirectMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # Content-Security-Policy header
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Required for user authentication
    'django_otp.middleware.OTPMiddleware',  # Two-Factor Authentication middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Inventory.middleware.UserRoleMiddleware',  # Custom middleware for role-based access
    # AxesMiddleware must be the LAST middleware in the stack.
    'axes.middleware.AxesMiddleware',
]


ROOT_URLCONF = 'Inventory_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Inventory.context_processors.user_profile',
                'Inventory.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inventory_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Pick a SQLite path that survives deploys on Azure. The previous default
# (BASE_DIR/db.sqlite3) lived under /tmp/<deployment-hash>/ on App Service,
# which Azure replaces on every push -- meaning a brand-new empty database on
# every deploy. /home/site/data/ is the persistent mount on App Service Linux.
if ON_AZURE_APP_SERVICE:
    try:
        os.makedirs(AZURE_PERSISTENT_DATA_DIR, exist_ok=True)
        _sqlite_path = os.path.join(AZURE_PERSISTENT_DATA_DIR, 'db.sqlite3')
    except OSError:
        # If /home/site/data isn't writable for any reason, fall back to BASE_DIR
        # so the app at least starts (data won't persist, but we'll log clearly).
        logging.warning(
            "Could not create %s; falling back to ephemeral BASE_DIR for SQLite. "
            "Data WILL be lost on deploy.", AZURE_PERSISTENT_DATA_DIR,
        )
        _sqlite_path = os.path.join(BASE_DIR, 'db.sqlite3')
else:
    _sqlite_path = os.path.join(BASE_DIR, 'db.sqlite3')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _sqlite_path,
    }
}

# Production database resolution.
#   1. DATABASE_URL / SCHEMATOGO_URL -- the ONLY supported production path
#      (PostgreSQL recommended). Connection pooling + SSL enabled by default.
#   2. ALLOW_SQLITE_IN_PROD=1 -- explicit, deliberate emergency override only.
#
# SECURITY/RELIABILITY: SQLite is NO LONGER auto-enabled in production. It
# serialises all writes (concurrent officers -> "database is locked" + lost
# writes) and has no safe concurrent backup story. Production now FAILS FAST
# unless a real database is configured. To avoid an outage on the deploy that
# introduces this change, set ALLOW_SQLITE_IN_PROD=1 in the App Service settings
# BEFORE deploying, then provision Postgres, set DATABASE_URL, and remove the
# flag to complete the migration (see HARDENING_PLAN.md, P0-1).
if not DEBUG:
    database_url = os.getenv('SCHEMATOGO_URL') or os.getenv('DATABASE_URL')
    allow_sqlite_prod = os.getenv('ALLOW_SQLITE_IN_PROD', '').lower() in ('1', 'true', 'yes')
    if database_url:
        DATABASES['default'] = dj_database_url.config(
            default=database_url,
            # Persistent connections reduce per-request connect overhead under load.
            conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '60')),
            conn_health_checks=True,
            # Require TLS to the database unless explicitly disabled.
            ssl_require=os.getenv('DB_SSL_REQUIRE', 'True').lower() == 'true',
        )
    elif allow_sqlite_prod:
        logging.warning(
            "Running in production on SQLite at %s. EMERGENCY OVERRIDE ONLY -- "
            "single-writer DB, do not run multi-user. Migrate to Postgres ASAP.",
            _sqlite_path,
        )
    else:
        raise ImproperlyConfigured(
            "Production database is not configured. Set DATABASE_URL (PostgreSQL) "
            "in the deployment environment. As a deliberate temporary measure only, "
            "set ALLOW_SQLITE_IN_PROD=1 -- but SQLite must not be used for "
            "concurrent multi-user production."
        )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Static files (CSS, JavaScript, Images)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = '/dashboard'
# All authentication is handled via Microsoft 365 OAuth
LOGIN_URL = '/auth/login/'
LOGOUT_REDIRECT_URL = 'index'
AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend MUST be first so lockouts are enforced before auth.
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOW_QUANTITY = 3

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Consolidated logging configured later

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ---------------------------------------------------------------------------
# File storage (Django 5.1 STORAGES API).
#   - "default"     = user-uploaded media. When Azure Blob credentials are
#                     present (production), uploads go to Blob so they survive
#                     deploys/restarts and work across multiple App Service
#                     instances. Falls back to local disk for dev and tests.
#   - "staticfiles" = WhiteNoise (compressed + manifest-hashed), as before.
# This replaces the legacy STATICFILES_STORAGE / DEFAULT_FILE_STORAGE settings,
# which Django 5.1 no longer reads (and which conflict with STORAGES if set).
# ---------------------------------------------------------------------------
AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME', '').strip()
AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY', '').strip()
AZURE_CONTAINER = os.getenv('AZURE_CONTAINER', '').strip()

_use_azure_media = bool(
    AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY and AZURE_CONTAINER and not TESTING
)

if _use_azure_media:
    _default_file_storage = {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
        "OPTIONS": {
            "account_name": AZURE_ACCOUNT_NAME,
            "account_key": AZURE_ACCOUNT_KEY,
            "azure_container": AZURE_CONTAINER,
            # The storage account has anonymous access disabled (correct — these
            # are sensitive documents), so serve uploads via short-lived SAS
            # URLs rather than public links.
            "expiration_secs": int(os.getenv('AZURE_URL_EXPIRATION_SECS', '3600')),
            # Don't silently overwrite an existing blob with the same name.
            "overwrite_files": False,
        },
    }
else:
    _default_file_storage = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }

STORAGES = {
    "default": _default_file_storage,
    "staticfiles": {
        # WhiteNoise compression WITHOUT manifest hashing. The manifest
        # ("...ManifestStaticFilesStorage") variant requires a built manifest
        # from `collectstatic` and raises on any missing {% static %} entry —
        # which breaks tests (no manifest) and would 500 production on a
        # missing asset (the templates reference at least one uncollected file,
        # e.g. css/index.css). Non-manifest still compresses + serves and
        # degrades gracefully. Re-enable the manifest variant later once all
        # static references are audited, if hashed cache-busting is wanted.
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Removed basicConfig to rely on Django LOGGING dict for Heroku console output

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'Inventory': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# =============================================================================
# EMAIL CONFIGURATION FOR PASSWORD RESET
# =============================================================================

# For development: Print emails to console
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'MOEN IMS <noreply@localhost>'
else:
    # For production: Use SMTP (Gmail example)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'MOEN IMS <noreply@moen-ims.org>')

# File upload limits
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024    # 10 MB
DATA_UPLOAD_MAX_NUMBER_FILES = 20

# =============================================================================
# CACHING & SCALABILITY
# =============================================================================
# Use Redis in production (REDIS_URL) for a shared cache across App Service
# instances; fall back to per-process local memory in dev / when unset.
# A shared cache is required before scaling out to >1 instance, and backs the
# rate limiter and axes lockout state below.
_redis_url = os.getenv('REDIS_URL', '').strip()
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'moen-ims-locmem',
        }
    }

# =============================================================================
# BRUTE-FORCE PROTECTION (django-axes)
# =============================================================================
# Protects password logins (notably Django admin) from credential stuffing.
# Disabled under the test runner: django-axes requires a `request` argument to
# authenticate(), which Django's test client.login() does not provide. This does
# NOT weaken production — axes is fully active outside tests.
AXES_ENABLED = not TESTING
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = float(os.getenv('AXES_COOLOFF_HOURS', '1'))  # hours before auto-unlock
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]           # lock on the pair, not IP alone
AXES_RESET_ON_SUCCESS = True
AXES_ENABLE_ACCESS_FAILURE_LOG = True
# Respect the proxy header so the real client IP is recorded behind Azure.
AXES_IPWARE_PROXY_COUNT = int(os.getenv('AXES_PROXY_COUNT', '1'))
AXES_IPWARE_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']

# =============================================================================
# RATE LIMITING (django-ratelimit)
# =============================================================================
# Applied as decorators on sensitive views (OAuth login/callback, bulk uploads).
RATELIMIT_ENABLE = os.getenv('RATELIMIT_ENABLE', 'True').lower() == 'true'
RATELIMIT_USE_CACHE = 'default'

# Per-endpoint limits (django-ratelimit rate strings), tunable via env so ops
# can tighten/loosen without a code change — same pattern as the AXES_* limits.
# These guard heavy/abusable endpoints: waybill PDF generation and bulk imports.
RATELIMIT_WAYBILL_PDF = os.getenv('RATELIMIT_WAYBILL_PDF', '10/m')
RATELIMIT_BULK_UPLOAD = os.getenv('RATELIMIT_BULK_UPLOAD', '6/m')
RATELIMIT_BULK_REQUEST = os.getenv('RATELIMIT_BULK_REQUEST', '6/m')

# =============================================================================
# CONTENT SECURITY POLICY (django-csp)
# =============================================================================
# Rolled out in REPORT-ONLY mode first so violations are reported without
# breaking the existing UI (Bootstrap, maps, Plotly, inline scripts). Review
# reports, tighten the directives, then switch the key to CONTENT_SECURITY_POLICY
# to enforce. Flip to enforcing via CSP_ENFORCE=1 once the report log is clean.
_csp_directives = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'", "'unsafe-eval'", 'https://cdn.jsdelivr.net',
                   'https://cdnjs.cloudflare.com', 'https://unpkg.com', 'https://code.jquery.com',
                   'https://cdn.plot.ly'),
    'style-src': ("'self'", "'unsafe-inline'", 'https://cdn.jsdelivr.net',
                  'https://cdnjs.cloudflare.com', 'https://fonts.googleapis.com', 'https://unpkg.com'),
    'font-src': ("'self'", 'https://fonts.gstatic.com', 'https://cdnjs.cloudflare.com', 'data:'),
    'img-src': ("'self'", 'data:', 'blob:', 'https:'),
    'connect-src': ("'self'", 'https:'),
    'frame-ancestors': ("'none'",),
}
if os.getenv('CSP_ENFORCE', '').lower() in ('1', 'true', 'yes'):
    CONTENT_SECURITY_POLICY = {'DIRECTIVES': _csp_directives}
else:
    CONTENT_SECURITY_POLICY_REPORT_ONLY = {'DIRECTIVES': _csp_directives}
