"""
Django settings for Inventory_management_system project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
import logging
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Prefer environment variable in production
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-6z-jao9@c1iv5^98mp_kq8)kfqo82k_u5@2-nj@s3*#76l*b=^'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'inventory-management-system-1-1bbd774008d3.herokuapp.com',
    'testserver',
    'moen-ims.org',
    '.moen-ims.org',
    'www.moen-ims.org',
    'moen-ims-28b53393a6a5.herokuapp.com',
    '.ondigitalocean.app',  # For DigitalOcean App Platform
]

# CSRF trusted origins (scheme required). Configure via env in production.
_default_csrf = [
    'https://localhost',
    'https://127.0.0.1',
    'https://moen-ims.org',
    'https://www.moen-ims.org',
    'https://inventory-management-system-1-1bbd774008d3.herokuapp.com',
    'https://moen-ims-28b53393a6a5.herokuapp.com',
    'https://moen-ims-gqcci.ondigitalocean.app/',
]
# Combine default CSRF trusted origins with any from environment
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
if not CSRF_TRUSTED_ORIGINS:  # Fall back to defaults if none provided
    CSRF_TRUSTED_ORIGINS = _default_csrf

# Add the current domain if not present
if 'CANONICAL_HOST' in os.environ and os.environ['CANONICAL_HOST']:
    host = os.environ['CANONICAL_HOST']
    for scheme in ('http://', 'https://'):
        origin = f"{scheme}{host}"
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

# Ensure request.is_secure() works behind proxies (DO App Platform / Heroku)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Optional: force a single canonical host (e.g., 'www.moen-ims.org') to avoid cross-host cookie issues
# Default to www.moen-ims.org in production if not provided via env. Empty in DEBUG.
CANONICAL_HOST = os.getenv('CANONICAL_HOST', ('' if DEBUG else 'www.moen-ims.org')).strip()

# Security settings for production
if not DEBUG:
    # HTTPS/SSL settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookie settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # Required for AJAX/JS
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # Set cookie domain if we have a canonical host
    if CANONICAL_HOST:
        domain = CANONICAL_HOST
        if domain.startswith('www.'):
            domain = domain[4:]
        if domain:  # Only set if domain is not empty
            SESSION_COOKIE_DOMAIN = f".{domain}"
            CSRF_COOKIE_DOMAIN = f".{domain}"
    
    # Security headers
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# Exempt certificate validation path from HTTPS redirect so CA bots can fetch
# HTTP-01 challenges without a valid certificate yet.
# Django's SecurityMiddleware honors this list when SECURE_SSL_REDIRECT is True.
SECURE_REDIRECT_EXEMPT = [r'^\.well-known/']



# Application definition

INSTALLED_APPS = [
    'Inventory',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'audit_log',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'Inventory.middleware.CanonicalHostRedirectMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Required for user authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Inventory.middleware.UserRoleMiddleware',  # Custom middleware for role-based access
]


ROOT_URLCONF = 'Inventory_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Inventory.context_processors.user_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inventory_management_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Default SQLite database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# If DATABASE_URL environment variable is set, use it to override the default
if os.getenv('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(default=os.getenv('DATABASE_URL'))


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Static files (CSS, JavaScript, Images)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = '/dashboard'
LOGIN_URL = 'signin'
LOGOUT_REDIRECT_URL = 'signin'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOW_QUANTITY = 3

STATIC_ROOT = BASE_DIR / 'staticfiles'


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Consolidated logging configured later

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Removed basicConfig to rely on Django LOGGING dict for Heroku console output

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO' if not DEBUG else 'DEBUG',
    },
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"