# Generated by Django 5.1.5 on 2026-03-05 11:07

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('ms_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('_access_token', models.TextField(blank=True, db_column='access_token', null=True)),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', auto_prefetch.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='microsoft_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Microsoft Credentials',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
