"""
Money-path tests: ReleaseLetter drawdown/fulfilment accounting and
MaterialOrder status integrity.

These cover the core logic that has historically broken (see KNOWN_ISSUES.md:
invalid 'Fulfilled' status, quantity accounting) and that the rest of the
inventory workflow depends on for correctness.
"""
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.test import TestCase

from Inventory.models import Unit, MaterialOrder, ReleaseLetter
from Inventory.models.transport import MaterialTransport


class ReleaseLetterAccountingTest(TestCase):
    """ReleaseLetter computed accounting properties."""

    def setUp(self):
        self.unit = Unit.objects.create(name="each")
        # Authorise 100 units on the letter.
        self.letter = ReleaseLetter.objects.create(
            request_code="REQ-001",
            title="Test Release Letter",
            total_quantity=Decimal("100"),
        )

    def _order(self, qty, **kwargs):
        return MaterialOrder.objects.create(
            name="Pole",
            quantity=Decimal(str(qty)),
            unit=self.unit,
            release_letter=self.letter,
            **kwargs,
        )

    def test_reference_number_autogenerated(self):
        self.assertTrue(self.letter.reference_number)
        self.assertTrue(self.letter.reference_number.startswith("RL-"))

    def test_total_requested_sums_linked_orders(self):
        self._order(30)
        self._order(20)
        self.assertEqual(self.letter.total_requested, Decimal("50"))

    def test_total_requested_zero_when_no_orders(self):
        self.assertEqual(self.letter.total_requested, Decimal("0"))

    def test_balance_to_request(self):
        self._order(40)
        self.assertEqual(self.letter.balance_to_request, Decimal("60"))

    def test_overdrawdown_is_rejected(self):
        # The release-letter balance guard must block requesting more than
        # the authorised quantity (80 + 40 > 100).
        self._order(80)
        with self.assertRaises(ValidationError):
            self._order(40)

    def test_drawdown_percentage(self):
        self._order(25)
        self.assertEqual(self.letter.drawdown_percentage, Decimal("25"))

    def test_drawdown_percentage_zero_when_total_quantity_zero(self):
        # Guard against division-by-zero in the percentage property.
        self.letter.total_quantity = Decimal("0")
        self.letter.save()
        self.assertEqual(self.letter.drawdown_percentage, Decimal("0"))

    def test_total_released_counts_only_delivered_transports(self):
        order = self._order(60)
        MaterialTransport.objects.create(
            material_order=order, quantity=Decimal("30"), status="Delivered"
        )
        MaterialTransport.objects.create(
            material_order=order, quantity=Decimal("20"), status="Loaded"
        )
        # Only the Delivered shipment counts toward physical fulfilment.
        self.assertEqual(self.letter.total_released, Decimal("30"))

    def test_fulfillment_gap_is_requested_minus_released(self):
        order = self._order(60)
        MaterialTransport.objects.create(
            material_order=order, quantity=Decimal("25"), status="Delivered"
        )
        # requested 60, released 25 -> gap 35 (committed but not yet delivered)
        self.assertEqual(self.letter.fulfillment_gap, Decimal("35"))

    def test_threshold_exceeded(self):
        self.letter.alert_threshold_percentage = Decimal("80")
        self.letter.save()
        self._order(85)
        self.assertTrue(self.letter.is_threshold_exceeded)


class MaterialOrderStatusIntegrityTest(TestCase):
    """Guards against the historical invalid-status regressions."""

    def test_invalid_fulfilled_status_not_in_choices(self):
        # Regression: code once set status='Fulfilled', which is not a valid
        # choice and caused 500s on release completion.
        codes = {c[0] for c in MaterialOrder.STATUS_CHOICES}
        self.assertNotIn("Fulfilled", codes)
        self.assertIn("Completed", codes)

    def test_default_status_is_draft(self):
        unit = Unit.objects.create(name="each")
        order = MaterialOrder.objects.create(
            name="Cable", quantity=Decimal("5"), unit=unit
        )
        self.assertEqual(order.status, "Draft")
