# Generated by Django 5.2.4 on 2025-08-17 13:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_billofquantity_group_alter_billofquantity_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('waybill_pdf', models.FileField(help_text='Upload the endorsed waybill PDF', upload_to='site_receipts/waybills/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('site_photos', models.FileField(help_text='Upload photos of materials at site', upload_to='site_receipts/photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the receipt', null=True)),
                ('condition', models.CharField(choices=[('Good', 'Good Condition'), ('Damaged', 'Damaged'), ('Partial', 'Partial Delivery')], default='Good', max_length=20)),
                ('material_transport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_receipt', to='Inventory.materialtransport')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Receipt',
                'verbose_name_plural': 'Site Receipts',
                'ordering': ['-received_date'],
            },
        ),
    ]
