# Generated by Django 5.2.4 on 2025-08-17 14:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_sitereceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create Project model
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('code', models.CharField(help_text='Unique project code', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('project_type', models.CharField(choices=[('Infrastructure', 'Infrastructure'), ('Construction', 'Construction'), ('Maintenance', 'Maintenance'), ('Emergency', 'Emergency')], default='Infrastructure', max_length=50)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('On Hold', 'On Hold'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=50)),
                ('consultant', models.CharField(help_text='Primary consultant for the project', max_length=200)),
                ('contractor', models.CharField(help_text='Primary contractor for the project', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, help_text='User responsible for managing this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_manage_projects', 'Can manage projects'), ('can_view_all_projects', 'Can view all projects')],
            },
        ),
        
        # Create ProjectSite model
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Site name or identifier', max_length=200)),
                ('code', models.CharField(help_text='Site code', max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('community', models.CharField(blank=True, max_length=100, null=True)),
                ('gps_coordinates', models.CharField(blank=True, help_text='GPS coordinates if available', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Planned', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='Inventory.project')),
                ('site_supervisor', models.ForeignKey(blank=True, help_text='User supervising this site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'code')},
            },
        ),
        
        # Create ProjectPhase model
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Phase name', max_length=200)),
                ('description', models.TextField(help_text='Phase description')),
                ('phase_order', models.PositiveIntegerField(help_text='Order of this phase in the project')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], default='Not Started', max_length=50)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.PositiveIntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='Inventory.project')),
            ],
            options={
                'ordering': ['project', 'phase_order'],
                'unique_together': {('project', 'phase_order')},
            },
        ),
        
        # Create Notification model
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('material_request', 'Material Request'), ('material_processed', 'Material Processed'), ('transport_assigned', 'Transport Assigned'), ('material_delivered', 'Material Delivered'), ('site_receipt_logged', 'Site Receipt Logged'), ('boq_updated', 'BOQ Updated'), ('staff_prompt', 'Staff Prompt')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recipient_group', models.CharField(choices=[('Schedule Officers', 'Schedule Officers'), ('Storekeepers', 'Storekeepers'), ('Management', 'Management'), ('Consultants', 'Consultants'), ('All', 'All Users')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Specific user recipient (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.materialorder')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.project')),
                ('related_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.materialtransport')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        
        # Add project fields to MaterialOrder
        migrations.AddField(
            model_name='materialorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.project'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='project_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.projectsite'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='project_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.projectphase'),
        ),
        
        # Add project fields to BillOfQuantity
        migrations.AddField(
            model_name='billofquantity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='Inventory.project'),
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='project_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.projectsite'),
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='project_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.projectphase'),
        ),
        
        # Add project fields to ReportSubmission
        migrations.AddField(
            model_name='reportsubmission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Inventory.project'),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='project_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.projectsite'),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='project_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.projectphase'),
        ),
        
        # Update SiteReceipt model to match our enhanced version
        migrations.AlterField(
            model_name='sitereceipt',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good Condition'), ('Damaged', 'Damaged'), ('Incomplete', 'Incomplete Delivery'), ('Poor Quality', 'Poor Quality')], default='Good', help_text='Condition of materials received', max_length=20),
        ),
        migrations.AddField(
            model_name='sitereceipt',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='received_by',
            field=models.ForeignKey(help_text='Consultant who logged this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Actual quantity received at site', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='waybill_pdf',
            field=models.FileField(help_text='Endorsed waybill in PDF format', upload_to='site_receipts/waybills/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='site_photos',
            field=models.FileField(help_text='Photos of materials at site', upload_to='site_receipts/photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the delivery'),
        ),
    ]
