# Generated by Django 5.2.4 on 2025-08-17 14:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_add_project_management_and_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofquantity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='billofquantity',
            name='project_phase',
        ),
        migrations.RemoveField(
            model_name='billofquantity',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='project',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='project_phase',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='project_phase',
        ),
        migrations.RemoveField(
            model_name='reportsubmission',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='sitereceipt',
            name='date_received',
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good Condition'), ('Damaged', 'Damaged'), ('Partial', 'Partial Delivery')], default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the receipt', null=True),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='received_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='site_photos',
            field=models.FileField(help_text='Upload photos of materials at site', upload_to='site_receipts/photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='waybill_pdf',
            field=models.FileField(help_text='Upload the endorsed waybill PDF', upload_to='site_receipts/waybills/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
