# Generated by Django 5.2.4 on 2025-08-24 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_remove_billofquantity_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the warehouse', max_length=200)),
                ('code', models.CharField(help_text='Unique warehouse code', max_length=50, unique=True)),
                ('location', models.CharField(help_text='Physical address or location description', max_length=500)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this warehouse is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the warehouse', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse associated with this BOQ item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where this item is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse associated with this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='materialtransport',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse where the material is being transported from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse associated with this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
    ]
