# Generated by Django 5.2.4 on 2025-08-24 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_warehouse_billofquantity_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the quantity was processed', null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the quantity for release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders_processed', to=settings.AUTH_USER_MODEL),
        ),
    ]
