# Generated by Django 4.2.25 on 2025-10-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_materialorder_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the supplier', max_length=200)),
                ('code', models.CharField(help_text='Unique supplier code', max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=200, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the supplier', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this supplier is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the supplier', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='materialorder',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for material receipts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.supplier'),
        ),
    ]
