# Generated by Django 5.2.7 on 2025-10-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_supplier_materialorder_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(help_text='Unique material code', max_length=200, unique=True),
        ),
    ]
