# Generated by Django 5.2.7 on 2025-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_supplier_materialorder_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(help_text='Material code', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('code', 'warehouse')},
        ),
    ]
