# Generated by Django 5.2.7 on 2025-10-22 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_unique_code_warehouse_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereceipt',
            name='acknowledgement_sheet',
            field=models.FileField(blank=True, help_text='Upload the signed acknowledgement sheet', null=True, upload_to='site_receipts/acknowledgements/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
