# Generated by Django 5.1.6 on 2025-03-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_billofquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofquantity',
            name='community',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
