# Generated by Django 5.2.7 on 2025-10-27 09:51

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_sitereceipt_acknowledgement_sheet'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofquantity',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name_plural': 'bills of quantity'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='materialorder',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-date_requested'], 'permissions': [('can_approve_order', 'Can approve material orders'), ('can_reject_order', 'Can reject material orders'), ('can_export_orders', 'Can export material orders')], 'verbose_name': 'Material Order', 'verbose_name_plural': 'Material Orders'},
        ),
        migrations.AlterModelOptions(
            name='materialorderaudit',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='materialtransport',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at'], 'verbose_name': 'Material Transport', 'verbose_name_plural': 'Material Transports'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at'], 'permissions': [('can_manage_projects', 'Can manage projects'), ('can_view_all_projects', 'Can view all projects')]},
        ),
        migrations.AlterModelOptions(
            name='projectphase',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['project', 'phase_order']},
        ),
        migrations.AlterModelOptions(
            name='projectsite',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['project', 'name']},
        ),
        migrations.AlterModelOptions(
            name='releaseletter',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-upload_time'], 'permissions': [('can_upload_release_letter', 'Can upload release letters')], 'verbose_name': 'Release Letter', 'verbose_name_plural': 'Release Letters'},
        ),
        migrations.AlterModelOptions(
            name='reportsubmission',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name_plural': 'report submissions'},
        ),
        migrations.AlterModelOptions(
            name='sitereceipt',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-received_date'], 'verbose_name': 'Site Receipt', 'verbose_name_plural': 'Site Receipts'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='transporter',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name'], 'verbose_name': 'Transporter', 'verbose_name_plural': 'Transporters'},
        ),
        migrations.AlterModelOptions(
            name='transportvehicle',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['transporter__name', 'registration_number'], 'verbose_name': 'Transport Vehicle', 'verbose_name_plural': 'Transport Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'base_manager_name': 'prefetch_manager', 'verbose_name_plural': 'units'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name'], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterModelManagers(
            name='billofquantity',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='inventoryitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materialorder',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materialorderaudit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materialtransport',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectphase',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projectsite',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='releaseletter',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reportsubmission',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sitereceipt',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='supplier',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transporter',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transportvehicle',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='warehouse',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Warehouse associated with this BOQ item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.unit'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='warehouse',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Warehouse where this item is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='category',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='created_by',
            field=auto_prefetch.ForeignKey(help_text='User who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='last_updated_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='User who last updated this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_material_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='processed_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='User who processed the quantity for release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='release_letter',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The release letter that authorizes this material order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders', to='Inventory.releaseletter'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='supplier',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Supplier for material receipts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='unit',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.unit'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='warehouse',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Warehouse associated with this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='materialorderaudit',
            name='order',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.materialorder'),
        ),
        migrations.AlterField(
            model_name='materialorderaudit',
            name='performed_by',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='created_by',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='material_order',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='Inventory.materialorder'),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='release_letter',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='Inventory.releaseletter'),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='transporter',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='Inventory.transporter'),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='vehicle',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='Inventory.transportvehicle'),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='warehouse',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Warehouse where the material is being transported from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_user',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Specific user recipient (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_order',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.materialorder'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_project',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.project'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_transport',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.materialtransport'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=auto_prefetch.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=auto_prefetch.ForeignKey(blank=True, help_text='User responsible for managing this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='project',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='Inventory.project'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='project',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='Inventory.project'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='site_supervisor',
            field=auto_prefetch.ForeignKey(blank=True, help_text='User supervising this site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='releaseletter',
            name='uploaded_by',
            field=auto_prefetch.ForeignKey(help_text='User who uploaded this letter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_release_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportsubmission',
            name='group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='reportsubmission',
            name='related_boq',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_submissions', to='Inventory.billofquantity'),
        ),
        migrations.AlterField(
            model_name='reportsubmission',
            name='user',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportsubmission',
            name='warehouse',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Warehouse associated with this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='material_transport',
            field=auto_prefetch.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_receipt', to='Inventory.materialtransport'),
        ),
        migrations.AlterField(
            model_name='sitereceipt',
            name='received_by',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportvehicle',
            name='transporter',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Inventory.transporter'),
        ),
    ]
