# Generated by Django 5.2.7 on 2025-10-28 15:39

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_alter_billofquantity_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoQOverissuanceJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.CharField(help_text='Project package number', max_length=50)),
                ('project_name', models.CharField(help_text='Project name/description', max_length=200)),
                ('overissuance_quantity', models.FloatField(help_text='Amount of overissuance')),
                ('reason', models.TextField(help_text='Detailed reason for overissuance')),
                ('justification_category', models.CharField(choices=[('Design Change', 'Design Change'), ('Site Condition', 'Site Condition'), ('Measurement Error', 'Measurement Error'), ('Emergency Need', 'Emergency Need'), ('Variation Order', 'Variation Order'), ('Other', 'Other')], help_text='Category of justification', max_length=100)),
                ('supporting_documents', models.TextField(blank=True, help_text='Reference to supporting documents or file paths')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Pending', help_text='Status of the justification', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, help_text='Comments from reviewer')),
                ('boq_item', auto_prefetch.ForeignKey(help_text='Bill of Quantity item with overissuance', on_delete=django.db.models.deletion.CASCADE, related_name='overissuance_justifications', to='Inventory.billofquantity')),
                ('reviewed_by', auto_prefetch.ForeignKey(blank=True, help_text='User who reviewed the justification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_overissuance_justifications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', auto_prefetch.ForeignKey(help_text='User who submitted the justification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_overissuance_justifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BoQ Overissuance Justification',
                'verbose_name_plural': 'BoQ Overissuance Justifications',
                'ordering': ['-submitted_at'],
                'permissions': [('can_review_overissuance', 'Can review overissuance justifications'), ('can_view_overissuance_summary', 'Can view overissuance summary')],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
