# Generated by Django 5.1.6 on 2025-03-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_billofquantity_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofquantity',
            name='contract_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='quantity_received',
            field=models.FloatField(default=0.0),
        ),
    ]
