# Generated by Django 5.2.7 on 2025-10-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_boqoverissuancejustification'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransport',
            name='consignment_number',
            field=models.CharField(blank=True, help_text='Groups multiple materials assigned together as one shipment', max_length=50, null=True),
        ),
    ]
