# Generated by Django 5.1.6 on 2025-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_alter_billofquantity_contract_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='category',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='code',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='name',
        ),
        migrations.AddField(
            model_name='materialorder',
            name='community',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='consultant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='contractor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='item_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='material_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='package_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='processed_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='remaining_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
