# Generated by Django 5.2.7 on 2025-10-31 15:21

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_add_consignment_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Supplier rating (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text="Supplier's invoice number", max_length=100, unique=True)),
                ('invoice_date', models.DateField(help_text='Date on the invoice')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=15)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('approved', 'Approved for Payment'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_document', models.FileField(blank=True, help_text='Scanned invoice document', null=True, upload_to='invoices/%Y/%m/')),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference number', max_length=200, null=True)),
                ('payment_date', models.DateField(blank=True, help_text='Date payment was made', null=True)),
                ('discrepancy_notes', models.TextField(blank=True, help_text='Notes about any discrepancies found', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_invoices', to=settings.AUTH_USER_MODEL)),
                ('supplier', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='Inventory.supplier')),
                ('verified_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'ordering': ['-invoice_date'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_invoiced', models.DecimalField(decimal_places=2, help_text='Quantity on the invoice', max_digits=15)),
                ('unit_rate_invoiced', models.DecimalField(decimal_places=2, help_text='Unit rate on the invoice', max_digits=15)),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity actually received (from MaterialOrder)', max_digits=15, null=True)),
                ('discrepancy_notes', models.TextField(blank=True, help_text='Notes about quantity/price discrepancies', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.supplierinvoice')),
                ('material', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='Inventory.inventoryitem')),
                ('material_order', auto_prefetch.ForeignKey(blank=True, help_text='Link to actual material order if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='Inventory.materialorder')),
                ('warehouse', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['material__name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Unique contract reference number', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Contract title/description', max_length=200)),
                ('contract_type', models.CharField(choices=[('one_time', 'One-Time Purchase'), ('framework', 'Framework Agreement'), ('long_term', 'Long-Term Contract')], default='one_time', max_length=20)),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(blank=True, help_text='Contract end date (null for open-ended)', null=True)),
                ('total_estimated_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total estimated contract value', max_digits=15)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Contract terms and conditions', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('supplier', auto_prefetch.ForeignKey(help_text='Supplier for this contract', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='Inventory.supplier')),
            ],
            options={
                'verbose_name': 'Supply Contract',
                'verbose_name_plural': 'Supply Contracts',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='contract',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Related contract (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='Inventory.supplycontract'),
        ),
        migrations.CreateModel(
            name='SupplyContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Contracted quantity', max_digits=15)),
                ('unit_rate', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.supplycontract')),
                ('material', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_items', to='Inventory.inventoryitem')),
                ('warehouse', auto_prefetch.ForeignKey(blank=True, help_text='Delivery warehouse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Contract Item',
                'verbose_name_plural': 'Contract Items',
                'ordering': ['material__name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPriceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_rate', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=15)),
                ('currency', models.CharField(default='GHS', help_text='Currency code (e.g., GHS, USD)', max_length=3)),
                ('effective_date', models.DateField(help_text='Date from which this price is valid')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when this price expires (null = no expiry)', null=True)),
                ('minimum_order_quantity', models.IntegerField(default=1, help_text='Minimum quantity that must be ordered')),
                ('lead_time_days', models.IntegerField(default=0, help_text='Number of days for delivery')),
                ('notes', models.TextField(blank=True, help_text='Additional pricing notes or conditions', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this price is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prices', to=settings.AUTH_USER_MODEL)),
                ('material', auto_prefetch.ForeignKey(help_text='Material being priced', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='Inventory.inventoryitem')),
                ('supplier', auto_prefetch.ForeignKey(help_text='Supplier offering this price', on_delete=django.db.models.deletion.CASCADE, related_name='price_catalog', to='Inventory.supplier')),
                ('warehouse', auto_prefetch.ForeignKey(blank=True, help_text='Warehouse this supplier delivers to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_prices', to='Inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Supplier Price',
                'verbose_name_plural': 'Supplier Prices',
                'ordering': ['-effective_date', 'supplier__name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('supplier', 'material', 'effective_date')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
