# Generated by Django 5.1.6 on 2025-03-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_remove_materialorder_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='community',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='district',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='material_description',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='package_number',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='region',
        ),
        migrations.AddField(
            model_name='materialorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='code',
            field=models.CharField(default='Enter code', max_length=200),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='processed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
