# Generated by Django 5.2.7 on 2025-11-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_materialorder_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digital_stamp',
            field=models.ImageField(blank=True, help_text='Auto-generated digital signature stamp', null=True, upload_to='digital_stamps/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stamp_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the digital stamp was generated', null=True),
        ),
    ]
