# Generated by Django 5.1.6 on 2025-03-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_materialorder_community_materialorder_consultant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='contract_quantity',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='material_description',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='quantity_received',
        ),
    ]
