# Generated by Django 5.2.7 on 2025-11-06 12:17

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_backfill_signature_stamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, help_text='Unique report identifier', max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(help_text='Start date of the reporting period')),
                ('end_date', models.DateField(help_text='End date of the reporting period')),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('executive_summary', models.TextField(help_text="Brief overview of the week's activities")),
                ('new_features', models.TextField(blank=True, help_text='New features implemented')),
                ('bug_fixes', models.TextField(blank=True, help_text='Bug fixes and issues resolved')),
                ('database_changes', models.TextField(blank=True, help_text='Database migrations and schema changes')),
                ('code_improvements', models.TextField(blank=True, help_text='Code refactoring and improvements')),
                ('pending_tasks', models.TextField(blank=True, help_text='Pending tasks and known issues')),
                ('next_priorities', models.TextField(blank=True, help_text="Next week's priorities")),
                ('custom_notes', models.TextField(blank=True, help_text='Custom notes added by the generator')),
                ('recipients', models.TextField(help_text='Comma-separated list of recipient emails')),
                ('cc_recipients', models.TextField(blank=True, help_text='Comma-separated list of CC emails')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the report was sent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('commits_analyzed', models.IntegerField(default=0, help_text='Number of git commits analyzed')),
                ('files_scanned', models.IntegerField(default=0, help_text='Number of documentation files scanned')),
                ('migrations_found', models.IntegerField(default=0, help_text='Number of migrations found')),
                ('html_content', models.TextField(blank=True, help_text='Full HTML email content')),
                ('plain_text_content', models.TextField(blank=True, help_text='Plain text email content')),
                ('generated_by', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'ordering': ['-generated_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
