# Generated by Django 5.2.7 on 2025-11-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_weeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF report', null=True, upload_to='weekly_reports/'),
        ),
    ]
