# Generated by Django 5.2.7 on 2025-11-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_profile_digital_stamp_profile_stamp_generated_at'),
        ('Inventory', '0017_weeklyreport_pdf_file'),
    ]

    operations = [
    ]
