# Generated by Django 5.1.6 on 2025-03-12 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_materialorderaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='category',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='code',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='group',
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='unit',
        ),
        migrations.AddField(
            model_name='materialorder',
            name='receipt_status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('On Site', 'On Site')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='community',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='consultant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='contractor',
            field=models.CharField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='district',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='package_number',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='region',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='request_type',
            field=models.CharField(choices=[('Release', 'Release'), ('Receipt', 'Receipt')], default='Receipt', max_length=10),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Seen', 'Seen'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
