# Generated by Django 5.2.7 on 2025-11-09 08:32

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_merge_20251107_1812'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='digital_stamp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stamp_generated_at',
        ),
        migrations.CreateModel(
            name='StoreOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Assignment'), ('Assigned', 'Assigned to Staff'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Reassigned', 'Reassigned')], default='Pending', help_text='Current status of this assignment', max_length=20)),
                ('assignment_notes', models.TextField(blank=True, help_text='Notes from store manager about this assignment', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes from stores staff upon completion', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the stores staff started working on this', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the assignment was completed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', auto_prefetch.ForeignKey(help_text='Store manager who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', auto_prefetch.ForeignKey(help_text='Stores staff member this order is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_store_orders', to=settings.AUTH_USER_MODEL)),
                ('material_order', auto_prefetch.ForeignKey(help_text='Material order being assigned to stores staff', on_delete=django.db.models.deletion.CASCADE, related_name='store_assignments', to='Inventory.materialorder')),
            ],
            options={
                'verbose_name': 'Store Order Assignment',
                'verbose_name_plural': 'Store Order Assignments',
                'ordering': ['-assigned_at'],
                'permissions': [('can_assign_orders', 'Can assign orders to stores staff'), ('can_view_all_assignments', 'Can view all order assignments')],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
