# Generated by Django 5.2.7 on 2025-11-09 09:04

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_remove_profile_digital_stamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the order was assigned to a storekeeper', null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='assigned_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Manager who assigned this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='assigned_to',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Storekeeper assigned to process this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_material_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
