# Generated by Django 5.1.6 on 2025-03-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_alter_materialorder_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialorder',
            options={'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='materialorder',
            name='receipt_status',
        ),
        migrations.AddField(
            model_name='materialorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='code',
            field=models.CharField(default='Enter code', max_length=200),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventory.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='community',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='consultant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='contractor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_material_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='package_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='request_type',
            field=models.CharField(choices=[('Release', 'Release Request'), ('Receipt', 'Receipt Request')], default='Release', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
