# Generated by Django 5.2.7 on 2025-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_materialorder_assigned_at_materialorder_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransport',
            name='waybill_download_count',
            field=models.IntegerField(default=0, help_text='Number of times this waybill has been downloaded'),
        ),
    ]
