# Generated by Django 5.1.6 on 2025-03-19 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0020_alter_materialorder_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('community', models.CharField(blank=True, max_length=100, null=True)),
                ('consultant', models.CharField(max_length=200)),
                ('contractor', models.CharField(max_length=200)),
                ('package_number', models.CharField(max_length=50)),
                ('material_description', models.CharField(max_length=200)),
                ('item_code', models.CharField(max_length=200)),
                ('contract_quantity', models.FloatField()),
                ('quantity_received', models.FloatField(default=0.0)),
                ('executive_summary', models.TextField(help_text='Provide a summary of the report')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('related_boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_submissions', to='Inventory.billofquantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'report submissions',
            },
        ),
    ]
