# Generated by Django 5.1.6 on 2025-03-21 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_reportsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsubmission',
            name='monthly_report',
            field=models.FileField(blank=True, help_text='Upload monthly report in PDF format', null=True, upload_to='monthly_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed')]),
        ),
    ]
