# Generated by Django 5.2.7 on 2025-11-20 11:15

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_add_waybill_download_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsoleteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Material name', max_length=200)),
                ('material_code', models.CharField(help_text='Material code', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Material category', max_length=200, null=True)),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of obsolete material', max_digits=10)),
                ('serial_numbers', models.TextField(blank=True, help_text='Serial numbers (for Energy Meters and Transformers). Enter one per line or comma-separated.', null=True)),
                ('reason_for_obsolescence', models.TextField(help_text='Explain why this material is obsolete (e.g., damaged, expired, outdated, excess stock)')),
                ('date_marked_obsolete', models.DateField(default=django.utils.timezone.now, help_text='Date when material was marked as obsolete')),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Pending Review', 'Pending Review'), ('Approved for Disposal', 'Approved for Disposal'), ('Disposed', 'Disposed'), ('Repurposed', 'Repurposed'), ('Returned to Supplier', 'Returned to Supplier')], default='Registered', help_text='Current status of the obsolete material', max_length=50)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated current value of the obsolete material', max_digits=12, null=True)),
                ('disposal_method', models.CharField(blank=True, help_text='Proposed or actual method of disposal', max_length=200, null=True)),
                ('disposal_date', models.DateField(blank=True, help_text='Date when material was disposed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments', null=True)),
                ('review_date', models.DateTimeField(blank=True, help_text='Date when the registration was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review process', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', auto_prefetch.ForeignKey(help_text='Select the material from inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.inventoryitem')),
                ('registered_by', auto_prefetch.ForeignKey(help_text='User who registered this obsolete material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsolete_materials_registered', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', auto_prefetch.ForeignKey(blank=True, help_text='User who reviewed this registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsolete_materials_reviewed', to=settings.AUTH_USER_MODEL)),
                ('warehouse', auto_prefetch.ForeignKey(blank=True, help_text='Warehouse where material is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Obsolete Material',
                'verbose_name_plural': 'Obsolete Materials',
                'ordering': ['-date_marked_obsolete', '-created_at'],
                'permissions': [('can_register_obsolete_material', 'Can register obsolete materials'), ('can_review_obsolete_material', 'Can review obsolete materials'), ('can_approve_disposal', 'Can approve material disposal')],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
