# Generated by Django 5.1.5 on 2026-01-26 16:33

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_obsoletematerial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releaseletter',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-upload_time'], 'permissions': [('can_upload_release_letter', 'Can upload release letters'), ('can_view_release_letter_tracking', 'Can view release letter tracking dashboard')], 'verbose_name': 'Release Letter', 'verbose_name_plural': 'Release Letters'},
        ),
        migrations.AddField(
            model_name='releaseletter',
            name='alert_threshold_percentage',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage threshold to trigger drawdown alerts (default 80%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='releaseletter',
            name='boq_item',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Bill of Quantity item for allocation validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_letters', to='Inventory.billofquantity'),
        ),
        migrations.AddField(
            model_name='releaseletter',
            name='material_type',
            field=models.CharField(choices=[('Transformers', 'Transformers'), ('Poles', 'Poles'), ('Cables', 'Cables'), ('Conductors', 'Conductors'), ('Meters', 'Meters'), ('Insulators', 'Insulators'), ('Switches', 'Switches'), ('Other', 'Other')], default='Other', help_text='Type of material covered by this release letter', max_length=50),
        ),
        migrations.AddField(
            model_name='releaseletter',
            name='project_phase',
            field=models.CharField(blank=True, help_text='Project phase this release letter covers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='releaseletter',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique reference number for this release letter (auto-generated if blank)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='releaseletter',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', help_text='Status of this release letter', max_length=10),
        ),
        migrations.AddField(
            model_name='releaseletter',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity authorized by this release letter', max_digits=12),
        ),
        migrations.AlterField(
            model_name='releaseletter',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='The signed release letter in PDF format', null=True, upload_to='release_letters/%Y/%m/%d/'),
        ),
    ]
