# Generated by Django 5.1.6 on 2025-03-24 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0022_reportsubmission_monthly_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.CharField(max_length=50)),
                ('material_description', models.CharField(max_length=200)),
                ('item_code', models.CharField(max_length=200)),
                ('contract_quantity', models.FloatField()),
                ('quantity_received', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'shipment orders',
            },
        ),
        migrations.CreateModel(
            name='ShipmentOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipment_order_trackings', to=settings.AUTH_USER_MODEL)),
                ('shipment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.shipmentorder')),
            ],
            options={
                'verbose_name_plural': 'shipment order trackings',
            },
        ),
    ]
