# Generated by Django 5.1.5 on 2026-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0023_alter_releaseletter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(blank=True, help_text='SHEP Phase (e.g., SHEP-4, Phase 2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('SHEP', 'SHEP'), ('Turnkey', 'Turnkey'), ('China Water', 'China Water'), ('Other Electrification', 'Other Electrification')], default='SHEP', max_length=50),
        ),
    ]
