# Generated by Django 5.1.6 on 2025-03-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0023_shipmentorder_shipmentordertracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentordertracking',
            name='shipment_order',
        ),
        migrations.RemoveField(
            model_name='shipmentordertracking',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='ShipmentOrder',
        ),
        migrations.DeleteModel(
            name='ShipmentOrderTracking',
        ),
    ]
