# Generated by Django 5.1.6 on 2025-04-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0024_remove_shipmentordertracking_shipment_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='media/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('material_code', models.CharField(max_length=200)),
                ('recipient', models.CharField(max_length=200)),
                ('consultant', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('community', models.CharField(blank=True, max_length=100, null=True)),
                ('package_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_transported', models.DateTimeField(auto_now_add=True)),
                ('date_received', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Loaded', 'Loaded'), ('En Route', 'En Route'), ('On Site', 'On Site')], max_length=20)),
                ('material_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.materialorder')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.releaseletter')),
            ],
        ),
    ]
