# Generated by Django 5.1.5 on 2026-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0024_project_phase_alter_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofquantity',
            name='phase',
            field=models.CharField(blank=True, help_text='SHEP Phase (e.g., SHEP-4)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='phase',
            field=models.CharField(blank=True, help_text='SHEP Phase (e.g., SHEP-4)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportsubmission',
            name='phase',
            field=models.CharField(blank=True, help_text='SHEP Phase (e.g., SHEP-4)', max_length=50, null=True),
        ),
    ]
