# Generated by Django 5.1.5 on 2026-02-08 16:12

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0025_billofquantity_phase_materialorder_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='project_type',
            field=models.CharField(choices=[('SHEP', 'SHEP'), ('COST', 'Cost-sharing'), ('SPEC', 'Special/other')], default='SHEP', help_text='Type of project this request is for', max_length=10),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='requestor',
            field=models.CharField(blank=True, help_text='Person/factory/institute making the request', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='requestor_abbr',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated requestor abbreviation', max_length=10),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the order was assigned to a store officer', null=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='assigned_to',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Store Officer assigned to process this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_material_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_group',
            field=models.CharField(choices=[('Schedule Officers', 'Schedule Officers'), ('Store Officers', 'Store Officers'), ('Management', 'Management'), ('Consultants', 'Consultants'), ('All', 'All Users')], max_length=20),
        ),
        migrations.CreateModel(
            name='SHEPCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Region name', max_length=100)),
                ('region_abbr', models.CharField(blank=True, editable=False, help_text='Auto-generated region abbreviation', max_length=10)),
                ('district', models.CharField(help_text='District name', max_length=100)),
                ('district_abbr', models.CharField(blank=True, editable=False, help_text='Auto-generated district abbreviation', max_length=10)),
                ('community', models.CharField(help_text='Community name', max_length=100)),
                ('community_abbr', models.CharField(blank=True, editable=False, help_text='Auto-generated community abbreviation', max_length=10)),
                ('package_number', models.CharField(help_text='SHEP package number for this community', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this community is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SHEP Community',
                'verbose_name_plural': 'SHEP Communities',
                'ordering': ['region', 'district', 'community'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('region', 'district', 'community', 'package_number')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
