# Generated by Django 5.1.5 on 2026-02-17 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0026_materialorder_project_type_materialorder_requestor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereceipt',
            name='waybill_pdf',
            field=models.FileField(blank=True, help_text='Upload the endorsed waybill PDF', null=True, upload_to='site_receipts/waybills/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
