# Generated by Django 5.1.5 on 2026-03-05 11:07

import auto_prefetch
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0027_make_waybill_pdf_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtransport',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-date_dispatched'], 'verbose_name': 'Material Transport', 'verbose_name_plural': 'Material Transports'},
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='community',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='consignment_number',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='date_assigned',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='date_departed',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='date_loaded',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='date_loading_started',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='destination_contact',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='destination_phone',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='district',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='material_code',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='package_number',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='region',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='release_letter',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='tracking_url',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='materialtransport',
            name='waybill_download_count',
        ),
        migrations.AddField(
            model_name='materialtransport',
            name='date_dispatched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='driver_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='driver_phone',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity being transported in this shipment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='status',
            field=models.CharField(choices=[('Loaded', 'Loaded / Ready'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Issue', 'Issue Reported')], default='Loaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='transporter',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.transporter'),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='vehicle',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.transportvehicle'),
        ),
        migrations.AlterField(
            model_name='materialtransport',
            name='waybill_number',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
