# Generated by Django 5.1.5 on 2026-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0028_alter_materialtransport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofquantity',
            name='community',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='item_code',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='package_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='region',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Partially Fulfilled', 'Partially Fulfilled'), ('Ready for Pickup', 'Ready for Pickup'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
