# Generated by Django 5.1.15 on 2026-05-18 09:35

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0046_refactor_phase_p2_supplier_contract_to_inventory'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signatory',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supply_contract',
            field=auto_prefetch.ForeignKey(blank=True, help_text="SupplyContract this stock batch was delivered under. Used to reconcile: 'How much of Contract #123 have we released to sites?'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='Inventory.supplycontract'),
        ),
    ]
