# Generated by Django 5.1.5 on 2026-05-18 12:58

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0047_alter_signatory_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('geom_json', models.JSONField(blank=True, help_text='GeoJSON boundary', null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['region', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phase', models.CharField(blank=True, db_index=True, help_text='SHEP Phase or other phase identifier (e.g., SHEP-4, Phase 2)', max_length=50, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('SHEP', 'SHEP'), ('Turnkey', 'Turnkey'), ('China Water', 'China Water'), ('Other Electrification', 'Other Electrification'), ('Other', 'Other')], max_length=100, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Planning', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('geom_json', models.JSONField(blank=True, help_text='GeoJSON boundary (used with SQLite)', null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='gps_coordinates',
            field=models.CharField(blank=True, help_text="GPS coordinates as 'lat,lon' format", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Community latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Community longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Site latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Site longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community',
            field=models.CharField(db_index=True, help_text='Community name', max_length=100),
        ),
        migrations.AlterField(
            model_name='community',
            name='district',
            field=models.CharField(db_index=True, help_text='District name', max_length=100),
        ),
        migrations.AlterField(
            model_name='community',
            name='region',
            field=models.CharField(db_index=True, help_text='Region name', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='community',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='region',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], db_index=True, default='Planned', max_length=50),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['region', 'district'], name='Inventory_c_region_1a5ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['region', 'district', 'community'], name='Inventory_c_region_83d253_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsite',
            index=models.Index(fields=['region', 'district'], name='Inventory_p_region_8f561a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsite',
            index=models.Index(fields=['region', 'status'], name='Inventory_p_region_01d732_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsite',
            index=models.Index(fields=['status', 'created_at'], name='Inventory_p_status_b3dc24_idx'),
        ),
        migrations.AddField(
            model_name='package',
            name='communities',
            field=models.ManyToManyField(help_text='Communities where this package will be implemented', related_name='packages', to='Inventory.community'),
        ),
        migrations.AddField(
            model_name='package',
            name='created_by',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='districts',
            field=models.ManyToManyField(help_text='Districts covered by this package', related_name='packages', to='Inventory.district'),
        ),
        migrations.AddField(
            model_name='package',
            name='region',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='Inventory.region'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['phase', 'status'], name='Inventory_p_phase_e110e4_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['region', 'status'], name='Inventory_p_region__1b1b39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name')},
        ),
    ]
