# Generated by Django 5.1.5 on 2026-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0048_district_package_region_community_gps_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'name', 'code')},
        ),
    ]
