# Generated by Django 5.1.5 on 2026-05-30 06:05

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0052_boq_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='linked_boq_item',
            field=auto_prefetch.ForeignKey(blank=True, help_text='For Overissuance Return receipts, the BoQ line being offset. BoQ.quantity_received is reduced by the processed quantity of this return when the receipt is completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_receipts', to='Inventory.billofquantity'),
        ),
    ]
