# Generated by Django 5.1.5 on 2026-05-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0053_alter_materialorder_linked_boq_item'),
        ('Inventory', '0053_release_letter_overrides'),
    ]

    operations = [
    ]
