# Generated by Django 5.1.5 on 2026-06-01 21:19

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0055_rename_streetlights_to_poles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='code',
            field=models.SlugField(help_text="Stable machine identifier, e.g. 'shep', 'cost_sharing', 'poles'.", unique=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(help_text="Display name, e.g. 'SHEP', 'Cost Sharing', 'Poles'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='releaseletter',
            name='letter_signatory_override',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Pick a specific signatory for the release letter to MMU. Leave blank to use the default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_overrides', to='Inventory.signatory'),
        ),
        migrations.AlterField(
            model_name='releaseletter',
            name='memo_to_override',
            field=models.CharField(blank=True, help_text="Memo TO line. Defaults to 'CHIEF DIRECTOR'. Set to 'AG. CHIEF DIRECTOR' etc. when needed.", max_length=200),
        ),
    ]
