# Generated by Django 5.1.5 on 2026-06-01 21:21
#
# Adds height_m / material_type / spec_notes columns to InventoryItem so the
# SKU becomes the source of truth for pole specifications. Includes a
# best-effort backfill: parse existing InventoryItem.name strings (e.g.
# "8m steel pole, octagonal") into the structured columns. Items that
# don't match the regex are left blank for admin cleanup -- no data loss.

import re
from decimal import Decimal, InvalidOperation

from django.conf import settings
from django.db import migrations, models


# Regex captures patterns like "8m", "8 m", "8.5m" anywhere in the name.
_HEIGHT_RE = re.compile(r'(\d+(?:\.\d+)?)\s*m\b', re.IGNORECASE)

# Material lexicon. Matching is case-insensitive and stops at the first hit
# so 'galvanised steel' resolves to 'steel' (not 'galvanised'); list more
# specific material keywords first if you want richer matches.
_MATERIAL_KEYWORDS = ('steel', 'concrete', 'wood', 'wooden', 'aluminium',
                      'aluminum', 'composite', 'fibreglass', 'fiberglass')


def _parse_name(name: str):
    """Return ``(height_m, material_type)`` parsed from a free-text name.

    Either component is ``None`` when not detected. Caller decides what to
    do with the result.
    """
    if not name:
        return (None, '')
    height = None
    m = _HEIGHT_RE.search(name)
    if m:
        try:
            height = Decimal(m.group(1))
        except InvalidOperation:
            height = None
    material = ''
    lower = name.lower()
    for kw in _MATERIAL_KEYWORDS:
        if kw in lower:
            # Normalise the few duplicates so reporting groups cleanly.
            material = {'wooden': 'wood', 'aluminum': 'aluminium',
                        'fiberglass': 'fibreglass'}.get(kw, kw)
            break
    return (height, material)


def backfill_specs(apps, schema_editor):
    """One-pass backfill of the three new columns from existing names.

    Only touches items whose category looks pole-like, so we don't sprinkle
    spurious heights onto cables or transformers. Items with no category or
    a non-pole category are skipped (columns remain blank).
    """
    InventoryItem = apps.get_model('Inventory', 'InventoryItem')

    # Heuristic for pole-related rows: name or category contains 'pole'.
    pole_qs = InventoryItem.objects.filter(name__icontains='pole')

    updated = 0
    for item in pole_qs.iterator(chunk_size=200):
        height, material = _parse_name(item.name or '')
        changed = False
        if height is not None and item.height_m is None:
            item.height_m = height
            changed = True
        if material and not item.material_type:
            item.material_type = material
            changed = True
        if changed:
            item.save(update_fields=['height_m', 'material_type'])
            updated += 1
    # No print() -- migrations should be quiet; the admin can audit via the
    # InventoryItem changelist after migrate completes.


def unbackfill_specs(apps, schema_editor):
    """Reverse: clear the three new columns. Used when this migration is
    rolled back; the column-drop happens automatically via the schema
    operations below this RunPython."""
    InventoryItem = apps.get_model('Inventory', 'InventoryItem')
    InventoryItem.objects.update(height_m=None, material_type='', spec_notes='')


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0056_alter_projecttype_code_alter_projecttype_name_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pole height in metres (poles only). Leave blank for non-pole materials.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='material_type',
            field=models.CharField(blank=True, help_text="Material composition, e.g. 'steel', 'concrete', 'wood'. Poles primarily; blank for materials where this doesn't apply.", max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='spec_notes',
            field=models.CharField(blank=True, help_text="Free-form spec fallback for attributes that don't fit the structured columns (e.g. 'octagonal', 'pre-stressed').", max_length=200),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['material_type', 'height_m'], name='Inventory_i_materia_bed4e7_idx'),
        ),
        migrations.RunPython(backfill_specs, reverse_code=unbackfill_specs),
    ]
