# Generated by Django 5.1.5 on 2026-06-01 21:22
#
# Creates MeterInstallation and AccessRateConfig (Track B Phase B1).
# Seeds one AccessRateConfig row with the agreed assumptions:
#   persons_per_connection    = 7        (household-size proxy)
#   baseline_population_access = 27,980,911   (pop. already electrified)
#   total_population          = 31,493,526    (national denominator)
#   effective_from            = 2026-01-01
# Update via a NEW row when better numbers land -- never mutate this one.

import datetime

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


def seed_initial_access_rate_config(apps, schema_editor):
    """Insert the agreed baseline config row if the table is empty."""
    AccessRateConfig = apps.get_model('Inventory', 'AccessRateConfig')
    if AccessRateConfig.objects.exists():
        return  # idempotent: never overwrite an admin-curated value
    AccessRateConfig.objects.create(
        persons_per_connection=7,
        baseline_population_access=27_980_911,
        total_population=31_493_526,
        effective_from=datetime.date(2026, 1, 1),
        notes=(
            'Initial seed -- agreed assumptions for the formula-based '
            'access-rate map. persons_per_connection=7 is a household-size '
            'proxy used until per-meter survey data is available. '
            'baseline_population_access and total_population are placeholders '
            'pending sign-off from the Ministry; refresh and add a new row '
            'rather than editing this one.'
        ),
    )


def unseed_initial_access_rate_config(apps, schema_editor):
    """Reverse: remove only the seed row (matches all three defaults)."""
    AccessRateConfig = apps.get_model('Inventory', 'AccessRateConfig')
    AccessRateConfig.objects.filter(
        persons_per_connection=7,
        baseline_population_access=27_980_911,
        total_population=31_493_526,
        effective_from=datetime.date(2026, 1, 1),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0057_inventoryitem_height_m_inventoryitem_material_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons_per_connection', models.PositiveIntegerField(default=7, help_text='People served per newly-installed meter. Default 7 = household-size proxy used when actual per-meter data is unavailable. Refresh when survey numbers improve.')),
                ('baseline_population_access', models.PositiveBigIntegerField(default=27980911, help_text="Population already electrified before the programme. Becomes the additive constant in the access-rate numerator. Source: cite in 'notes' when changing.")),
                ('total_population', models.PositiveBigIntegerField(default=31493526, help_text='Total national population (denominator). Refresh from the latest census when published.')),
                ('effective_from', models.DateField(db_index=True, help_text="First date this config applies. The current config is the row with the latest effective_from <= today's date.")),
                ('notes', models.TextField(blank=True, help_text='Why these values? Cite the source (e.g. "GSS 2021 census, Ministry briefing of 12 May 2026"). Shown on the map info panel so reviewers can audit the numbers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_rate_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access rate config',
                'verbose_name_plural': 'access rate configs',
                'ordering': ['-effective_from'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MeterInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(choices=[('1ph', '1-phase'), ('3ph', '3-phase')], db_index=True, help_text="'1ph' for single-phase, '3ph' for three-phase meters. Both feed the access rate at the same weight (each meter ≈ one household).", max_length=3)),
                ('quantity', models.PositiveIntegerField(help_text='Number of meters of this phase type installed on this report. Use one row per phase_type per day; do not mix.')),
                ('installation_date', models.DateField(db_index=True, help_text='Date the meters were energised at site. Used for as-of access-rate queries.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Set automatically when verified_by is filled in by the verification view.', null=True)),
                ('evidence_photo', models.ImageField(blank=True, help_text='Optional photo of the installed meter(s). Helps the verifier sign off without a site visit.', null=True, upload_to='meter_evidence/')),
                ('notes', models.TextField(blank=True, help_text='Optional context (which feeder, which transformer, cluster name, anything the verifier should know).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', auto_prefetch.ForeignKey(help_text='Community where the meters were installed. Drives the region / district roll-ups on the access-rate map.', on_delete=django.db.models.deletion.PROTECT, related_name='meter_installations', to='Inventory.community')),
                ('project_site', auto_prefetch.ForeignKey(blank=True, help_text='Optional. Link the installation to a specific ProjectSite when the community has more than one active site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_installations', to='Inventory.projectsite')),
                ('reported_by', auto_prefetch.ForeignKey(help_text='Field officer / site supervisor who logged the install.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', auto_prefetch.ForeignKey(blank=True, help_text='Manager who confirmed the install. Only verified rows contribute to the published access rate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meter installation',
                'verbose_name_plural': 'meter installations',
                'ordering': ['-installation_date', '-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['phase_type', 'installation_date'], name='Inventory_m_phase_t_0d6368_idx'), models.Index(fields=['community', 'phase_type'], name='Inventory_m_communi_9faa4d_idx'), models.Index(fields=['verified_at'], name='Inventory_m_verifie_ab48dd_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(
            seed_initial_access_rate_config,
            reverse_code=unseed_initial_access_rate_config,
        ),
    ]
