# Generated by Django 5.1.5 on 2026-06-01 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0058_accessrateconfig_meterinstallation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='works_status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Energised', 'Energised'), ('Commissioned', 'Commissioned')], db_index=True, default='Planned', help_text='Physical-works progress. Driven by verified MeterInstallation rows: any verified install at the community flips this to "Energised". Commissioning is set manually by the supervisor. Use this for access-rate roll-ups; use ``status`` only for material-flow views.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectsite',
            index=models.Index(fields=['region', 'works_status'], name='Inventory_p_region_2bfa49_idx'),
        ),
    ]
