# Generated by Django 5.1.5 on 2026-06-02 21:51

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0060_revert_poles_to_streetlights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='progress_notes',
            field=models.TextField(blank=True, help_text='Brief context from the consultant. Shown on the map drill-down.'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consultant-reported % complete (0-100). Updated from the Site Progress page. Drives the Ghana map headline in the interim.'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, help_text='Stamped automatically when progress_percent or works_status changes.', null=True),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='progress_updated_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Last user who updated the progress record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_progress_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='works_status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Energised', 'Energised'), ('Commissioned', 'Commissioned')], db_index=True, default='Planned', help_text='Physical-works progress. Two write paths feed this: (1) consultants update it from the Site Progress page; (2) verified MeterInstallation rows flip it to "Energised" when the access-rate-from-meters flow is enabled. Use this for access-rate roll-ups; use ``status`` only for material-flow views.', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='code',
            field=models.SlugField(help_text="Stable machine identifier, e.g. 'shep', 'cost_sharing', 'streetlights'.", unique=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='name',
            field=models.CharField(help_text="Display name, e.g. 'SHEP', 'Cost Sharing', 'Streetlights'.", max_length=100),
        ),
    ]
