# Generated by Django 5.1.5 on 2026-06-05 07:13

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0062_projectsite_material_quantities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billofquantity',
            name='voltage_class',
            field=models.CharField(blank=True, choices=[('HT', 'HT (high tension)'), ('LV', 'LV (low tension)'), ('XFMR', 'Transformer'), ('METER', 'Meter / service connection'), ('OTHER', 'Other / non-line')], db_index=True, default='', help_text='Explicit HT/LV/Transformer/Meter classification. Authoritative when set; the keyword heuristic only pre-fills a suggestion. Used to seed community progress targets at setup.', max_length=10),
        ),
        migrations.AddField(
            model_name='community',
            name='planned_connections',
            field=models.PositiveIntegerField(default=0, help_text='Planned service connections / meters (denominator for the meters stage).'),
        ),
        migrations.AddField(
            model_name='community',
            name='planned_ht_conductor_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned HT conductor in metres (reference; not a completion denominator).', max_digits=12),
        ),
        migrations.AddField(
            model_name='community',
            name='planned_ht_poles',
            field=models.PositiveIntegerField(default=0, help_text='Planned HT poles (denominator for HT-works stage).'),
        ),
        migrations.AddField(
            model_name='community',
            name='planned_lv_conductor_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned LV conductor in metres (reference; not a completion denominator).', max_digits=12),
        ),
        migrations.AddField(
            model_name='community',
            name='planned_lv_poles',
            field=models.PositiveIntegerField(default=0, help_text='Planned LV poles (denominator for LV-works stage).'),
        ),
        migrations.AddField(
            model_name='community',
            name='planned_transformers',
            field=models.PositiveIntegerField(default=0, help_text='Planned transformers (denominator for transformer + commissioning stages).'),
        ),
        migrations.AddField(
            model_name='community',
            name='targets_locked',
            field=models.BooleanField(default=False, help_text='When set, a BoQ pull will not overwrite these targets (manual baseline frozen).'),
        ),
        migrations.AddField(
            model_name='community',
            name='targets_pulled_at',
            field=models.DateTimeField(blank=True, help_text='When targets were last pulled from BoQ.', null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='targets_pulled_by',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Who last pulled targets from BoQ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_target_pulls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='targets_source',
            field=models.CharField(blank=True, choices=[('manual', 'Entered manually'), ('boq_pull', 'Pulled from BoQ')], default='manual', help_text='How the planned targets were last set.', max_length=10),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='ht_conductor_strung_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HT conductor used for stringing to date, in metres.', max_digits=10),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='ht_poles_dressed',
            field=models.PositiveIntegerField(default=0, help_text='HT poles dressed (hardware fitted) to date.'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='ht_poles_erected',
            field=models.PositiveIntegerField(default=0, help_text='HT poles erected/planted at this site to date.'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='ht_poles_strung',
            field=models.PositiveIntegerField(default=0, help_text='HT poles strung (conductor run) to date.'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='lv_conductor_strung_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='LV conductor used for stringing to date, in metres.', max_digits=10),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='lv_poles_dressed',
            field=models.PositiveIntegerField(default=0, help_text='LV poles dressed (hardware fitted) to date.'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='lv_poles_erected',
            field=models.PositiveIntegerField(default=0, help_text='LV poles erected/planted at this site to date.'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='lv_poles_strung',
            field=models.PositiveIntegerField(default=0, help_text='LV poles strung (conductor run) to date.'),
        ),
    ]
