# Generated by Django 5.2.15 on 2026-06-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0064_backfill_progress_rework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_timeliness', models.PositiveIntegerField(default=30)),
                ('weight_quality', models.PositiveIntegerField(default=30)),
                ('weight_throughput', models.PositiveIntegerField(default=20)),
                ('weight_responsiveness', models.PositiveIntegerField(default=20)),
                ('min_items_for_grade', models.PositiveIntegerField(default=5, help_text="Below this many completed items in the period, show 'Insufficient data' instead of a grade.")),
            ],
            options={
                'verbose_name': 'Performance configuration',
                'verbose_name_plural': 'Performance configuration',
            },
        ),
        migrations.CreateModel(
            name='RolePerformanceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text="Group name this target applies to (e.g. 'Store Officers').", max_length=50, unique=True)),
                ('sla_days', models.PositiveIntegerField(default=3, help_text="Max days for this role's stage to count as on-time.")),
                ('throughput_target', models.PositiveIntegerField(default=20, help_text="Completed items per 30 days that equals 'meeting expectation' (100%).")),
                ('quality_target_pct', models.PositiveIntegerField(default=95, help_text='Quality rate (%) that equals full marks (e.g. % deliveries with no damage).')),
                ('stage_label', models.CharField(blank=True, help_text='Human description of the stage measured (for dashboards).', max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Role performance target',
                'verbose_name_plural': 'Role performance targets',
                'ordering': ['role'],
            },
        ),
        migrations.AlterField(
            model_name='community',
            name='package_number',
            field=models.CharField(blank=True, help_text='Package number for this community under its project type. Used across programmes (SHEP, Cost Sharing, Streetlights) to track releases and reconcile them to a specific BoQ package line.', max_length=50),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Seen', 'Seen'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Partially Fulfilled', 'Partially Fulfilled'), ('Ready for Pickup', 'Ready for Pickup'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveIntegerField()),
                ('timeliness_score', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('throughput_score', models.FloatField(blank=True, null=True)),
                ('responsiveness_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=4)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('on_time_count', models.PositiveIntegerField(default=0)),
                ('insufficient_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance snapshot',
                'verbose_name_plural': 'Performance snapshots',
                'ordering': ['-period_year', '-period_month', '-overall_score'],
                'indexes': [models.Index(fields=['period_year', 'period_month'], name='Inventory_p_period__54641d_idx')],
                'unique_together': {('user', 'period_year', 'period_month')},
            },
        ),
    ]
