# Generated by Django 5.2.15 on 2026-06-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0066_seed_performance_targets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'code'), ('region', 'name')},
        ),
    ]
