# Generated by Django 5.1.15 on 2026-07-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0072_justification_supporting_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('material_request', 'Material Request'), ('material_processed', 'Material Processed'), ('transport_assigned', 'Transport Assigned'), ('material_delivered', 'Material Delivered'), ('site_receipt_logged', 'Site Receipt Logged'), ('boq_updated', 'BOQ Updated'), ('staff_prompt', 'Staff Prompt'), ('security_alert', 'Security Alert')], max_length=30),
        ),
    ]
