# Generated by Django 5.1.15 on 2026-08-09 10:15

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0089_discussion_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signingstep',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['order', 'document_kind'], 'verbose_name': 'signing step', 'verbose_name_plural': 'signing steps'},
        ),
        migrations.AlterModelManagers(
            name='archivedrequisition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='discussionrequest',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='documentdispatch',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='documentsignature',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='letterhead',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='releasecodesequence',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='signingstep',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='archivedrequisition',
            new_name='Inventory_a_documen_553af5_idx',
            old_name='inv_arch_date_type_idx',
        ),
        migrations.AlterField(
            model_name='archivedrequisition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentdispatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentsignature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letterhead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectconsultant',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='Optional legacy fallback. Narrows binding to specific districts when no area match is found.', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectconsultant',
            name='region',
            field=models.CharField(blank=True, db_index=True, help_text="Legacy / single-region fallback. Prefer setting an Area. Only used when no area covers the community's region.", max_length=100),
        ),
        migrations.AlterField(
            model_name='releasecodesequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signingstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
