# Generated by Django 5.1.15 on 2026-08-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0077_area_project_scoping'),
        ('Inventory', '0091_boq_assistance_notification'),
    ]

    operations = [
    ]
