# Generated by Django 5.1.15 on 2026-09-03 12:59

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0094_notification_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, help_text='Low-stock threshold. When quantity drops to or below this, the tally card flags a reorder. 0 disables the flag.'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening balance'), ('receipt', 'Receipt (stock in)'), ('issue', 'Issue / release (stock out)'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('adjustment', 'Adjustment (stock count)'), ('write_off', 'Write-off / obsolete'), ('reversal', 'Reversal')], db_index=True, max_length=20)),
                ('qty_in', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qty_out', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item', auto_prefetch.ForeignKey(help_text='The stock record (material + warehouse) this movement acts on.', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Inventory.inventoryitem')),
                ('performed_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['created_at', 'id'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'indexes': [models.Index(fields=['item', 'created_at'], name='Inventory_s_item_id_0eb240_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
