# Generated by Django 5.1.15 on 2026-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0096_seed_opening_stock_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtransport',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Quantity being transported in this shipment. Nullable: an 'Awaiting Transporter' placeholder row is created before a quantity is known, and save() already guards for None.", max_digits=10, null=True),
        ),
    ]
