# Generated by Django 5.1.15 on 2026-09-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0097_alter_materialtransport_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit used to value stock on the valuation report (quantity x unit_cost). Seeded from the latest supplier catalogue price and editable thereafter. 0 = unpriced.', max_digits=15),
        ),
    ]
