"""
Phase F.1 PDF generator service.

Produces two documents per release event:

  generate_release_memo(release_letter)
    Internal memorandum from Ag. Director, Power to the Chief Director
    seeking approval to release materials from MMU. Mirrors the structure
    of REQUEST FOR A REPLACEMENT OF TRANSFORMER THE HEAD OF STATE AWARD
    SCHEME.docx -- TO/FROM/DATE/SUBJECT block at top, body prose, signature.

  generate_release_letter(release_letter)
    External letter from MOEN to the MMU manager directing release of the
    materials to the consignee (consultant for SHEP, MP for Cost Sharing /
    Streetlights). Mirrors the structure of RELEASE LETTER MINISTRY OF
    EDUCATION.docx -- addressee block, bold subject, body, signature
    block ("FOR: HON. MINISTER"), cc list. QR code with the release code
    in the top-right corner so scan uploads can be matched back to this
    specific release event.

Both functions return Django ContentFile instances ready to assign to a
FileField. The caller is responsible for persisting them on the
ReleaseLetter row and committing the transaction.
"""

import io
import logging
from datetime import datetime

from django.core.files.base import ContentFile
from django.utils import timezone

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def generate_release_memo(release_letter):
    """
    Generate the approval memo PDF for a release. Returns a ContentFile
    suitable for assignment to ReleaseLetter.memo_pdf.
    """
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    ctx = _build_memo_context(release_letter)

    # Header: MEMORANDUM centered, bold
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawCentredString(width / 2, height - 35 * mm, "MEMORANDUM")

    # QR code top-right (encodes the release code so the memo can be matched
    # back to its sibling release letter and scan upload at audit time).
    qr_size = 22 * mm
    qr_x = width - qr_size - 15 * mm
    qr_y = height - qr_size - 10 * mm
    qr_image = _render_qr_code(ctx['code'])
    if qr_image is not None:
        pdf.drawImage(qr_image, qr_x, qr_y, width=qr_size, height=qr_size, mask='auto')
    pdf.setFont("Helvetica", 8)
    pdf.drawRightString(width - 15 * mm, qr_y - 3 * mm, ctx['code'])

    # TO/FROM/DATE/SUBJECT block
    y = height - 55 * mm
    line_height = 6 * mm
    label_x = 20 * mm
    value_x = 55 * mm

    pdf.setFont("Helvetica-Bold", 10)
    for label, value in [
        ("TO:", ctx['memo_to']),
        ("FROM:", ctx['memo_from']),
        ("DATE:", ctx['date']),
        ("SUBJECT:", ctx['memo_subject']),
    ]:
        pdf.drawString(label_x, y, label)
        pdf.setFont("Helvetica", 10)
        # Wrap subject if it's long
        wrapped_lines = _wrap_text(value, max_width=width - value_x - 20 * mm, font_size=10)
        for line in wrapped_lines:
            pdf.drawString(value_x, y, line)
            y -= line_height
        pdf.setFont("Helvetica-Bold", 10)

    y -= 4 * mm  # extra space before body

    # Body paragraphs
    pdf.setFont("Helvetica", 11)
    body_paragraphs = _build_memo_body(release_letter, ctx)
    for paragraph in body_paragraphs:
        wrapped = _wrap_text(paragraph, max_width=width - 40 * mm, font_size=11)
        for line in wrapped:
            if y < 50 * mm:
                pdf.showPage()
                pdf.setFont("Helvetica", 11)
                y = height - 30 * mm
            pdf.drawString(20 * mm, y, line)
            y -= 5.5 * mm
        y -= 4 * mm  # paragraph break

    # Signature block
    y -= 20 * mm  # leave space for wet signature
    if y < 60 * mm:
        pdf.showPage()
        y = height - 60 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, ctx['memo_signatory_name'].upper())
    y -= 5 * mm
    pdf.setFont("Helvetica", 10)
    if ctx['memo_signatory_title']:
        pdf.drawString(20 * mm, y, ctx['memo_signatory_title'].upper())
        y -= 5 * mm

    # Footer
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.drawCentredString(width / 2, 15 * mm,
                          f"System-generated by MOEN-IMS — Release event {ctx['code']} — "
                          f"Generated {timezone.now().strftime('%d %B %Y, %H:%M')}")

    pdf.save()
    buffer.seek(0)
    return ContentFile(buffer.getvalue(), name=f"memo_{ctx['code']}.pdf")


def generate_release_letter(release_letter):
    """
    Generate the release letter PDF to MMU. Returns a ContentFile suitable
    for assignment to ReleaseLetter.letter_pdf.

    Includes a QR code in the top-right corner encoding the release code
    so uploaded scans can be matched back to this release event.
    """
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    ctx = _build_letter_context(release_letter)

    # Letterhead placeholder space (top ~30mm reserved for pre-printed letterhead).
    # In production this can be replaced with a drawImage() call.
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.setFillGray(0.55)
    pdf.drawString(20 * mm, height - 12 * mm,
                   "[ Ministry of Energy and Green Transition — letterhead reserved ]")
    pdf.setFillGray(0)

    # QR code in top-right
    qr_size = 25 * mm
    qr_x = width - qr_size - 15 * mm
    qr_y = height - qr_size - 12 * mm
    qr_image = _render_qr_code(ctx['code'])
    if qr_image is not None:
        pdf.drawImage(qr_image, qr_x, qr_y, width=qr_size, height=qr_size, mask='auto')
    # Code printed below the QR for human reading.
    pdf.setFont("Helvetica", 8)
    pdf.drawRightString(width - 15 * mm, qr_y - 3 * mm, ctx['code'])

    # Date right-aligned below the QR
    pdf.setFont("Helvetica", 10)
    pdf.drawRightString(width - 15 * mm, qr_y - 9 * mm, ctx['date'])

    # Recipient block (left-aligned, ~45mm from top of body area)
    y = height - 55 * mm
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(20 * mm, y, "THE MANAGER")
    y -= 5.5 * mm
    pdf.drawString(20 * mm, y, "MATERIALS MANAGEMENT UNIT")
    y -= 5.5 * mm
    pdf.drawString(20 * mm, y, "KPONE-TEMA")
    y -= 12 * mm

    # Subject — bold, all caps, centered
    pdf.setFont("Helvetica-Bold", 11)
    subject_lines = _wrap_text(ctx['letter_subject'], max_width=width - 40 * mm, font_size=11)
    for line in subject_lines:
        pdf.drawCentredString(width / 2, y, line)
        y -= 5.5 * mm
    y -= 6 * mm

    # Body paragraphs
    pdf.setFont("Helvetica", 11)
    body_paragraphs = _build_letter_body(release_letter, ctx)
    for paragraph in body_paragraphs:
        wrapped = _wrap_text(paragraph, max_width=width - 40 * mm, font_size=11)
        for line in wrapped:
            if y < 60 * mm:
                pdf.showPage()
                pdf.setFont("Helvetica", 11)
                y = height - 30 * mm
            pdf.drawString(20 * mm, y, line)
            y -= 5.5 * mm
        y -= 4 * mm  # paragraph break

    # Signature block: NAME / TITLE / FOR: HON. MINISTER
    y -= 22 * mm  # leave space for wet signature
    if y < 70 * mm:
        pdf.showPage()
        y = height - 70 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, ctx['letter_signatory_name'].upper())
    y -= 5 * mm
    pdf.setFont("Helvetica", 10)
    if ctx['letter_signatory_title']:
        pdf.drawString(20 * mm, y, ctx['letter_signatory_title'].upper())
        y -= 5 * mm
    if ctx['letter_signatory_signs_for']:
        pdf.drawString(20 * mm, y, f"FOR: {ctx['letter_signatory_signs_for'].upper()}")
        y -= 8 * mm

    # CC list
    if ctx['cc_list']:
        pdf.setFont("Helvetica-Oblique", 9)
        pdf.drawString(20 * mm, y, "cc:")
        y -= 4.5 * mm
        for cc in ctx['cc_list']:
            if y < 25 * mm:
                pdf.showPage()
                y = height - 30 * mm
            pdf.drawString(25 * mm, y, cc)
            y -= 4.5 * mm

    # Footer
    pdf.setFont("Helvetica-Oblique", 8)
    pdf.drawCentredString(width / 2, 12 * mm,
                          f"System-generated by MOEN-IMS — Release event {ctx['code']} — "
                          f"Validate the scanned signed copy by checking the QR code.")

    pdf.save()
    buffer.seek(0)
    return ContentFile(buffer.getvalue(), name=f"letter_{ctx['code']}.pdf")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _build_memo_context(release_letter):
    """Pull the variable substitution data for the memo template."""
    from Inventory.models import Signatory

    signatory = Signatory.for_release_memo()
    orders = release_letter.material_orders.all() if release_letter.pk else []
    first_order = orders[0] if orders else None

    return {
        'code': release_letter.code or '(pending)',
        'date': timezone.now().strftime('%d %B %Y').upper(),
        'memo_to': 'CHIEF DIRECTOR',
        'memo_from': (signatory.title if signatory else 'DIRECTOR, POWER').upper(),
        'memo_subject': _build_subject(release_letter, orders),
        'memo_signatory_name': signatory.name if signatory else '',
        'memo_signatory_title': '',  # FROM line already shows the title
        'first_order': first_order,
        'orders': orders,
        'project_type': release_letter.project_type or 'SHEP',
    }


def _build_letter_context(release_letter):
    """Pull the variable substitution data for the release letter template."""
    from Inventory.models import Signatory

    signatory = Signatory.for_release_letter()
    orders = release_letter.material_orders.all() if release_letter.pk else []

    return {
        'code': release_letter.code or '(pending)',
        'date': timezone.now().strftime('%d %B %Y').upper(),
        'letter_subject': _build_subject(release_letter, orders).upper(),
        'letter_signatory_name': signatory.name if signatory else '',
        'letter_signatory_title': signatory.title if signatory else 'CHIEF DIRECTOR',
        'letter_signatory_signs_for': signatory.signs_for if signatory else 'HON. MINISTER',
        'orders': orders,
        'project_type': release_letter.project_type or 'SHEP',
        'cc_list': _build_cc_list(release_letter, orders),
    }


def _build_subject(release_letter, orders):
    """Compose a subject line from the materials and beneficiary."""
    if not orders:
        return release_letter.title or "REQUEST FOR RELEASE OF MATERIALS"

    first = orders[0] if not hasattr(orders, 'first') else orders.first()
    if first is None:
        return release_letter.title or "REQUEST FOR RELEASE OF MATERIALS"

    qty = first.quantity
    unit = first.unit.name if first.unit_id else 'no.'
    material = first.name or 'materials'
    location = first.community or first.district or ''
    location_phrase = f" AT {location.upper()}" if location else ""

    return (
        f"REQUEST FOR RELEASE OF {qty}{unit.upper()} {material.upper()}"
        f"{location_phrase}"
    )


def _build_memo_body(release_letter, ctx):
    """Compose the body paragraphs of the approval memo."""
    first_order = ctx.get('first_order')
    project_type = ctx.get('project_type', 'SHEP')

    if not first_order:
        return [
            "We write to seek approval for the release of materials from the Ministry's "
            "Materials Management Unit (MMU) for the project listed in this release event.",
            "We have attached the release letter for sign-off.",
        ]

    qty = first_order.quantity
    unit = first_order.unit.name if first_order.unit_id else 'no.'
    material = first_order.name or 'materials'
    location = first_order.community or first_order.district or 'the project site'

    if project_type == 'SHEP':
        beneficiary_phrase = (
            f"the Self-Help Electrification Project (SHEP) at {location}"
        )
    elif project_type == 'COST':
        beneficiary_phrase = (
            f"the Cost Sharing programme at {location}"
        )
    elif project_type == 'STREET':
        beneficiary_phrase = (
            f"the Streetlights programme at {location}"
        )
    else:
        beneficiary_phrase = f"the project at {location}"

    return [
        f"We write to seek approval for the release of {qty} {unit} of {material} "
        f"from the Ministry's Materials Management Unit (MMU) for {beneficiary_phrase}.",

        "MMU has confirmed the availability of the materials in stock.",

        f"A release letter to MMU is attached for sign-off, referenced "
        f"under release event {ctx['code']}.",
    ]


def _build_letter_body(release_letter, ctx):
    """Compose the body paragraphs of the release letter to MMU."""
    orders = ctx.get('orders') or []
    project_type = ctx.get('project_type', 'SHEP')

    if not orders:
        return [
            "I refer to the stock of materials at the Materials Management Unit (MMU), Kpone-Tema.",
            "You are hereby directed to release the materials listed under "
            f"release event {ctx['code']} to the consignee identified in our records.",
        ]

    first = orders[0] if not hasattr(orders, 'first') else orders.first()

    qty = first.quantity
    unit = first.unit.name if first.unit_id else 'no.'
    material = first.name or 'materials'
    region = first.region or ''
    district = first.district or ''
    community = first.community or 'the project site'

    location_phrase = community
    if district:
        location_phrase += f" in the {district}"
    if region:
        location_phrase += f", {region} Region"

    stock_phrase = {
        'SHEP': 'SHEP materials/equipment',
        'COST': 'Cost-sharing materials',
        'STREET': 'Streetlights materials',
    }.get(project_type, 'materials')

    consignee_phrase = first.consultant or first.contractor or 'the project consignee'

    return [
        f"I refer to the stock of {stock_phrase} at the Materials Management Unit (MMU), Kpone-Tema.",

        f"You are hereby directed to release via the Ministry's Inventory Management System (IMS), "
        f"{qty} {unit} of {material} to {consignee_phrase}, "
        f"to carry out the installation work at {location_phrase}.",

        f"We are by a copy of this letter requesting {consignee_phrase} and the relevant local stakeholders "
        f"to contact you for the release of the materials for installation.",
    ]


def _build_cc_list(release_letter, orders):
    """Build the cc distribution list. Per-project defaults plus the consignee."""
    project_type = release_letter.project_type or 'SHEP'

    base = [
        "The Hon. Minister, MoEn&GT",
        "The Hon. Deputy Minister, MoEn&GT",
        "Ag. Director, Power, MoEn&GT",
        "Director, Internal Audit Unit, MoEn&GT",
    ]
    if project_type == 'SHEP':
        base.append("Ag. Managing Director, NEDCo / ECG (as applicable)")
    elif project_type == 'COST':
        base.append("Hon. Member of Parliament (constituency)")
    elif project_type == 'STREET':
        base.append("Hon. Member of Parliament (constituency)")
        base.append("Metropolitan / Municipal / District Chief Executive (MMDCE)")

    base.append("The Beneficiary")
    return base


def _wrap_text(text, max_width, font_size):
    """Crude word-wrap. Returns a list of lines that fit within max_width."""
    from reportlab.pdfbase.pdfmetrics import stringWidth

    if not text:
        return ['']
    words = str(text).split()
    if not words:
        return ['']
    lines = []
    current = words[0]
    for word in words[1:]:
        candidate = current + ' ' + word
        if stringWidth(candidate, "Helvetica", font_size) <= max_width:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def _render_qr_code(payload):
    """Render the release code as a QR code. Returns a ReportLab ImageReader
    object, or None if qrcode library isn't available (degrades to no QR)."""
    try:
        import qrcode
        from reportlab.lib.utils import ImageReader
    except ImportError:
        logger.warning("qrcode library not installed; release letter will lack QR code.")
        return None

    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=10,
        border=1,
    )
    qr.add_data(payload)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    buffer = io.BytesIO()
    img.save(buffer, format='PNG')
    buffer.seek(0)
    return ImageReader(buffer)
